### ISSUE TITLE
Usage of Wire library.

### ISSUE THREAD

**Issue by Koepel** [VCSFA-MARS/TSLPB#1]
In the file "TSLPB/src/TSLPB.cpp" the function "read8bitRegister()" is good, but the function "read16bitRegister()" has writing and reading mixed.
See also my [alternative explanation of the functions of the Wire library](https://github.com/Koepel/How-to-use-the-Arduino-Wire-library/wiki/Explanation-of-the-functions-of-the-Wire-library).

**Comment by nickcounts** [comment]
@Koepel thanks for catching that. I'm away from my hardware, so I haven't re-tested yet, but it should be correct now in the develop branch from this commit: https://github.com/VCSFA-MARS/TSLPB/commit/1d38f85a82adc8483841744ac008b91e000edc2e 

Frustrating that I appear to have written it correctly, and then commented out the `endTransmission()` and added it back in after the `requestFrom()`.

**Comment by nickcounts** [comment]
Fix implemented and released in https://github.com/VCSFA-MARS/TSLPB/commit/c095b9ed990ff547af33452f7b19b30d4d4483b9
